version: "3.8"

services: 
    app:
        image: kanban_app:dev
        build: "./kanban-frontend/"
        command: sh -c "npm install && npm run serve"
        volumes:
            - ./kanban-frontend:/app
        ports:
            - 80:8080