version: "3.8"

services: 
    reverse_proxy:
        image: kanban_reverse_proxy:dev
        build: ./reverse_proxy/
        ports:
            - 80:80
        depends_on: 
            - app
            - api
    app:
        image: kanban_app:dev
        build: ./app
        command: sh -c "npm install && npm run serve"
        volumes:
            - ./app:/app
    api:
        image: kanban_api:dev
        build: "./api/"
        command: sh -c "npm install && npm start"
        volumes:
            - ./api:/api
        depends_on: 
            - db
    db:
        image: kanban_db:dev
        build: ./db/
        environment: 
            POSTGRES_PASSWORD: changeme
            POSTGRES_USER: postgres
        # command: sh -c "adduser kanban-dev -D && su kanban-dev && pg_restore -d kanban-dev -1 kanban-dev-backup && postgres"
        # command: sh -c "postgres"

